### PR TITLE
Protocol for r/21_u2 NetworkProtocolVersion 712

### PR DESCRIPTION
**Pull request by oswaldolb**
# Minecraft Network Protocol Docs 07/16/2024
For r21u2, Network Protocol Version 712

## New Packets

CurrentStructureFeaturePacket:
* Added mCurrentStructureFeature (string)

ServerboundDiagnosticsPacket:
* Added mTelemetry.mAvgFps (float)
* Added mTelemetry.mAvgServerSimTickTimeMS (float)
* Added mTelemetry.mAvgClientSimTickTimeMS (float)
* Added mTelemetry.mAvgBeginFrameTimeMS (float)
* Added mTelemetry.mAvgInputTimeMS (float)
* Added mTelemetry.mAvgRenderTimeMS (float)
* Added mTelemetry.mAvgEndFrameTimeMS (float)
* Added mTelemetry.mAvgRemainderTimePercent (float)
* Added mTelemetry.mAvgUnaccountedTimePercent (float)

## Packet Changes

InventoryContentPacket:
* Added mDynamicContainerId (uint32_t)

InventorySlotPacket:
* Added mDynamicContainerId (uint32_t)

ResourcePacksInfoPacket:
* Added pack.mIsAddonPack (bool) under mData.mBehaviorPacks
* Added pack.mIsAddonPack (bool) under mData.mResourcePacks

## Additional Types Added

FullContainerName:
* Added containerName.mName (enum ContainerEnumName)
* Added containerName.mDynamicId.mData (uint32_t)

TargetInstruction:
* Added mTargetCenterOffset (brstd::optional<Vec3>)
* Added mTargetActorId (int64_t)

## Additional Types Changed

CameraInstruction:
* Added mTarget (brstd::optional<TargetInstruction>)
* Added mRemoveTarget (brstd::optional<bool>)

ItemStackRequestSlotInfo:
* Removed mOpenContainerNetId
* Added mFullContainerName (FullContainerName)

ItemUseInventoryTransaction:
* Added mTriggerType (enum ItemUseInventoryTransaction::TriggerType) [description below]

## New Enums

ItemUseInventoryTransaction::TriggerType:
* Added Unknown(0)
* Added PlayerInput(1)
* Added SimulationTick(2)

## Enum Changes

ActorEvent:
* Added DEPRECATED_UPDATE_STRUCTURE_FEATURE(66)
* Removed UPDATE_STRUCTURE_FEATURE

Connection::DisconnectFailReason:
* Added SubClientLoginDisabled(116)

ContainerEnumName:
* Added DynamicContainer(63)

MinecraftPacketIds:
* Added CurrentStructureFeaturePacket(314)
* Added ServerboundDiagnosticsPacket(315)
* Displaced EndId

### CODE REVIEW

**Comment by Adrian8115** [comment]
Are these changelogs purely the changes between the protocol versions 686 and 712 or the prior not shipped R21_U1 and 712?

**Comment by Kaooot** [comment]
@Adrian8115 I believe these are the changes between v705 and v712 as v686 only adds the ClientboundCloseFormPacket which was supposed to be added in v705 but since that version never shipped, the packet was added in the v686 hotfix and that seems to be the only change in the hotfix.

**Comment by yshroff-dev** [comment]
@Adrian8115 / @Kaooot : Thanks for the callout, we probably missed pulling in [this](https://github.com/Mojang/bedrock-protocol-docs/blob/r/21_u1/changelog_705_06_13_24.md) file as part of the PR.

**Comment by Kaooot** [comment]
@yshroff-dev By the way, could you please add the documentation for ItemStackRequest actions to the protocol documentation? (https://bugs.mojang.com/browse/WEB-7226). It seems that v693 changed something in some actions. However, these changes still seem to be present in the latest preview. All in all, I found out that the byte that indicates how many times a recipe has been crafted ("numberOfRequestedCrafts") has been added to:
- ItemStackRequestActionCraftCreative
- ItemStackRequestActionCraftGrindstone
- ItemStackRequestActionCraftRecipe

**Review by yshroff-dev — APPROVED** [review]
Looks good, we probably want to pull in the changelog from U1.

**Comment by Adrian8115** [comment]
Looks great, thank y'all very much for your amazing work!

**Pull request merged**
