### PR TITLE
spelling issue/grammar issue

### PR DESCRIPTION
**Pull request by notchyves**
idk what it's considered but that's **NOT** how you spell "release"

### CODE REVIEW

**Comment by Adrian8115** [comment]
Lmao 1:0 for notchyves against mojang

**Comment by mdisprgm** [comment]
congrats, first PR that will be merged lol

**Review by yshroff-dev — APPROVED** [review]

**Comment by NSPC911** [comment]
No way blud had his change approved like that, like how did they just decide, you know what, lets give this guy contributor for fixing a spelling mistake

**Comment by hmm-monke** [comment]
> No way blud had his change approved like that, like how did they just decide, you know what, lets give this guy contributor for fixing a spelling mistake

calm down

**Comment by NSPC911** [comment]
no, just kinda comedic, thats all

**Comment by notchyves** [comment]
🤭

**Pull request merged**
